spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/VISA_STUDENT_DB?createDatabaseIfNotExist=true
    username: root
    password: Welcome123
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQLDialect
        show-sql:true
        format_sql:true
